name: Run e2e tests

on:
  # schedule:
  #   - cron: "0 8-20/2 * * *" # every 2 hours / working hours
  workflow_dispatch:

jobs:
  run-desktop-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pw-tests-image -f tests/ui/Dockerfile .

      - name: Run Desktop Playwright tests
        run: |
          docker run --rm \
          -e BASE_URL="${{ vars.APP_BASE_URL }}" \
          -v "$GITHUB_WORKSPACE/allure-results:/app/allure-results" \
          -v "$GITHUB_WORKSPACE/playwright-report-desktop:/app/playwright-report" \
          pw-tests-image npm run test -- --project="chromium" --project="firefox" --project="webkit"
        env:
          CI: true

      - name: Upload desktop test report artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-desktop
          path: playwright-report-desktop/
          retention-days: 3

  run-mobile-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pw-tests-image -f tests/ui/Dockerfile .

      - name: Run Mobile Playwright tests
        run: |
          docker run --rm \
          -e BASE_URL="${{ vars.APP_BASE_URL }}" \
          -v "$GITHUB_WORKSPACE/allure-results:/app/allure-results" \
          -v "$GITHUB_WORKSPACE/playwright-report-mobile:/app/playwright-report" \
          pw-tests-image npm run test -- --project="Mobile Chrome" --project="Mobile Safari"
        env:
          CI: true

      - name: Upload mobile test report artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-mobile
          path: playwright-report-mobile/
          retention-days: 3


  notify-telegram:
    runs-on: ubuntu-latest
    needs: [ run-desktop-tests, run-mobile-tests ]
    if: failure()
    steps:
      - name: Send TG notification when test run fails
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_E2E_ALERTS_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            **${{ github.ref_name || 'main' }}: ton-society tests failed **
            
            See details and report in [job](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)
