name: Frontend e2e tests2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, staging ]

  schedule:
     #- cron: "*/30 * * * *" # every 30 minutes
     - cron: "0 0 * * *" # every night
  workflow_dispatch:
    inputs:
      baseUrl:
        description: 'Base url for run'
        required: true
        default: 'https://society.ton.org'
        options:
          - 'https://society.ton.org'
          - 'https://stg.globalsociety.xyz'

env:
  baseUrl: ${{ github.event.inputs.baseUrl == '' && 'https://society.ton.org' || github.event.inputs.baseUrl }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pw-tests-image .

      - name: Run Playwright tests in Docker container
        run: docker run --rm -v "${{ github.workspace }}/allure-results:/app/allure-results" pw-tests-image

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 1

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages

      - name: Print the link to the report
        run: echo "https://nimestel.github.io/playwright-example-tests/${{ github.run_number }}"

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          target_url: https://nimestel.github.io/playwright-example-tests/${{ github.run_number }}
