name: common e2e test run config

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
      baseUrl:
        description: 'app url for test run'
        type: string
        required: true
    secrets: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pw-tests-image .

      - name: Run Playwright tests in Docker container
        run: docker run --rm \
         -e BASE_URL="${{ inputs.baseUrl }}" \
         -v "/home/runner/work/playwright-example-tests/playwright-example-tests/allure-results:/app/allure-results" \
         -v "/home/runner/work/playwright-example-tests/playwright-example-tests/playwright-report:/app/playwright-report" \
         pw-tests-image
        env:
          CI: true

      - name: Upload allure report artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 3

      - name: Upload playwright report artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3

      - name: Send TG notification when test run fails
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_E2E_ALERTS_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            **${{ inputs.env_name }}: ton-society tests fails **

            See details and report in [job](${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)
