name: common e2e test run config

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
      baseUrl:
        description: 'app url for test run'
        type: string
        required: true
    secrets: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pw-tests-image .

      - name: Run Playwright tests in Docker container
        run: docker run --rm -v "${{ github.workspace }}/allure-results:/app/allure-results" -v "${{ github.workspace }}/playwright-report:/app/playwright-report" pw-tests-image
        env:
          CI: true
          baseUrl: ${{ inputs.baseUrl }}

      - name: Upload allure report artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 2

      - name: Upload playwright report artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2

      - name: Get Report ID
        id: get_report_id
        if: always()
        run: |
          token="${{ secrets.GITHUB_TOKEN }}"
          run_id="${{ github.run_id }}"
          repository="${{ github.repository }}"
          response=$(curl -s -X GET \
            -H "Authorization: Bearer $token" \
            "https://api.github.com/repos/$repository/actions/runs/$run_id/artifacts")
    
          echo "Response: $response"  # debug
      
          # Extracting artifact_id from the response
          artifact_id=$(echo $response | jq -r '.artifacts[] | select(.name == "playwright-report").id')
          
          echo "artifact_id=$artifact_id"

      - name: Send TG notification when test run fails
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_E2E_ALERTS_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            **${{ inputs.env_name }}: ton-society tests fails **

            See details in [job](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
            Test report: [Playwright report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.get_report_id.outputs.artifact_id }})
